"""init

Revision ID: 112a846a3807
Revises: 
Create Date: 2025-11-11 10:24:31.870434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112a846a3807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('sucursal', sa.String(length=120), nullable=True),
    sa.Column('fecha_incorporacion', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('demora_despacho_promedio_dias', sa.Integer(), nullable=True),
    sa.Column('plazo_pago_promedio_dias', sa.Integer(), nullable=True),
    sa.Column('mail_pedido', sa.String(length=255), nullable=True),
    sa.Column('mail_pago', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('client_company_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TRABAJA', 'TRABAJABA', 'A_INCORPORAR', name='relationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'company_id', name='uq_client_company')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sucursal', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'CHEQUE', 'TRANSFERENCIA', 'NO_SE_SABE', name='paymentmethod'), nullable=True),
    sa.Column('demora_despacho_promedio_dias', sa.Integer(), nullable=True),
    sa.Column('mail_pedido', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega_efectiva', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'CHEQUE', 'TRANSFERENCIA', 'NO_SE_SABE', name='paymentmethod'), nullable=True),
    sa.Column('fecha_pago_estimada', sa.DateTime(), nullable=True),
    sa.Column('fecha_cobro_efectiva', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('logistics_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_efectiva', sa.DateTime(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pago', sa.Enum('EFECTIVO', 'CHEQUE', 'TRANSFERENCIA', 'NO_SE_SABE', name='paymentmethod'), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logistics_status')
    op.drop_table('collection')
    op.drop_table('order')
    op.drop_table('client_company_link')
    op.drop_table('company')
    op.drop_table('client')
    # ### end Alembic commands ###
