"""add binary storage to client_document

Revision ID: 20946727b627
Revises: 48da9ad2834a
Create Date: 2025-11-17 16:34:30.439657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20946727b627'
down_revision = '48da9ad2834a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_document', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
