"""add cuit to company

Revision ID: 5f0bb2797381
Revises: 20946727b627
Create Date: 2025-12-10 13:36:29.282299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0bb2797381'
down_revision = '20946727b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_company_link', schema=None) as batch_op:
        batch_op.alter_column('comprobante_tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FACTURA'"))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cuenta_bancaria_notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('cuenta_bancaria_notas')
        batch_op.drop_column('notas')
        batch_op.drop_column('cuit')

    with op.batch_alter_table('client_company_link', schema=None) as batch_op:
        batch_op.alter_column('comprobante_tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FACTURA'"))

    # ### end Alembic commands ###
